### ISSUE TITLE
Routing Get Involved to the Upcoming Events on the Home Page

### ISSUE THREAD

**Issue by emilyywangg** [TechPlus-UW/Portal-FE#105]
While we wait on the Portal and a Sponsor page which will likely be added to the website, the Get Involved just links to an empty page. 

From discussions, it seems like most users are going to the website to get information about our events so linking it to the Upcoming Events Section would be the most useful. 

![image](https://user-images.githubusercontent.com/51860039/108611711-290b2780-73af-11eb-9b5d-5ae4c2ecf02c.png)

**Comment by jack-lin-jql** [comment]
@emilyywangg Let's just remove the Get Involved from the NavBar for now. Let me know if you think differently!

**Comment by jack-lin-jql** [comment]
![image](https://user-images.githubusercontent.com/13803465/109375954-084f4000-788f-11eb-9c26-09414d90242d.png)

Reopening as the Get Involved tab is still showing. Perhaps there was a build issue?

**Comment by kerry918** [comment]
![image](https://user-images.githubusercontent.com/56353549/109392722-b8eb2d00-78eb-11eb-86d8-ad697b139b17.png)

I just pushed the 'copy check update' and the Get Involved tab is being removed. 
I think it's good now.
