### ISSUE TITLE
React-ify team profile + events section

### ISSUE THREAD

**Issue by keyualiceli** [TechPlus-UW/Portal-FE#28]
-not a priority, for future maintainability-
Right now these sections are hardcoded in. It would be nice to put them into structures and loop through each with just a single display for their div

**Comment by jack-lin-jql** [comment]
@hyunzeekim  I think this is done as part of our updates for the landing page, can you please check and act accordingly?

**Comment by hyunzeekim** [comment]
Verified that this has already been done as part of our updates for the landing page
